src/Entity/Student.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\StudentRepository;

#[ORM\Entity(repositoryClass: StudentRepository::class)]
class Student
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'string', length: 255)]
    private $surname;

    #[ORM\Column(type: 'datetime')]
    private $date_naissance;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $date_inscrit;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $photo;

    #[ORM\Column(type: 'string', length: 255)]
    private $sexe;

    #[ORM\Column(type: 'text', nullable: true)]
    private $info_perso;

    #[ORM\ManyToOne(targetEntity: Tuteur::class, inversedBy: 'students')]
    private $tuteur;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getDateNaissance(): ?\datetime
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\datetime $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getDateInscrit(): ?\DateTimeInterface
    {
        return $this->date_inscrit;
    }

    public function setDateInscrit(\DateTimeInterface $date_inscrit): self
    {
        $this->date_inscrit = $date_inscrit;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getInfoPerso(): ?string
    {
        return $this->info_perso;
    }

    public function setInfoPerso(?string $info_perso): self
    {
        $this->info_perso = $info_perso;

        return $this;
    }

    public function getTuteur(): ?Tuteur
    {
        return $this->tuteur;
    }

    public function setTuteur(?Tuteur $tuteur): self
    {
        $this->tuteur = $tuteur;

        return $this;
    }

    public function __toString(): string
    {
         return (string) $this->getSurname();
    }

}

src/Form/StudentType.php
<?php

namespace App\Form;

use App\Entity\Student;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class StudentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class)
            ->add('surname', TextType::class)
            ->add('date_naissance', DateTimeType::class)
            ->add('photo', TextType::class)
            ->add('sexe', TextType::class)
            ->add('info_perso', TextareaType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Student::class,
        ]);
    }
}

src/Controller/StudentController.php
<?php

namespace App\Controller;

use App\Entity\Student;
use App\Form\StudentType;
use App\Repository\StudentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/student')]
class StudentController extends AbstractController
{
    #[Route('/', name: 'student_index', methods: ['GET'])]
    public function index(StudentRepository $studentRepository): Response
    {
        return $this->render('student/index.html.twig', [
            'students' => $studentRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'student_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $student = new Student();
        $form = $this->createForm(StudentType::class, $student);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($student);
            $entityManager->flush();

            return $this->redirectToRoute('student_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('student/new.html.twig', [
            'student' => $student,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'student_show', methods: ['GET'])]
    public function show(Student $student): Response
    {
        return $this->render('student/show.html.twig', [
            'student' => $student,
        ]);
    }

    #[Route('/{id}/edit', name: 'student_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Student $student, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(StudentType::class, $student);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('student_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('student/edit.html.twig', [
            'student' => $student,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'student_delete', methods: ['POST'])]
    public function delete(Request $request, Student $student, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$student->getId(), $request->request->get('_token'))) {
            $entityManager->remove($student);
            $entityManager->flush();
        }

        return $this->redirectToRoute('student_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/student/_delete_form.html.twig
<form method="post" action="{{ path('student_delete', {'id': student.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ student.id) }}">
    <button class="btn">Delete</button>
</form>

templates/student/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/student/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Student{% endblock %}

{% block body %}
    <h1>Edit Student</h1>

    {{ include('student/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('student_index') }}">back to list</a>

    {{ include('student/_delete_form.html.twig') }}
{% endblock %}

templates/student/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Student index{% endblock %}

{% block body %}
    <h1>Student index</h1>

    {# {{ component('studentpost', {}) }} #}

<p> <a href="{{ path('student_new') }}" class="btn btn-primary">Create new</a></p>
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Surname</th>
                <th>Date_naissance</th>
                <th>Date_inscrit</th>
                <th>Photo</th>
                <th>Sexe</th>
                <th>Info_perso</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for student in students %}
            <tr>
                <td>{{ student.id }}</td>
                <td>{{ student.name }}</td>
                <td>{{ student.surname }}</td>
                <td>{{ student.dateNaissance ? student.dateNaissance|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ student.dateInscrit ? student.dateInscrit|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ student.photo }}</td>
                <td>{{ student.sexe }}</td>
                <td>{{ student.infoPerso }}</td>
                <td>
                    <a href="{{ path('student_show', {'id': student.id}) }}" class="btn btn-info btn-small">show</a>
                    <a href="{{ path('student_edit', {'id': student.id}) }}" class="btn btn-primary btn-small">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('student_new') }}" class="btn btn-primary">Create new</a>
{% endblock %}

templates/student/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Student{% endblock %}

{% block body %}
    <h1>Create new Student</h1>

    {{ include('student/_form.html.twig') }}

    <a href="{{ path('student_index') }}">back to list</a>
{% endblock %}

templates/student/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Student{% endblock %}

{% block body %}
    <h1>Student</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ student.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ student.name }}</td>
            </tr>
            <tr>
                <th>Surname</th>
                <td>{{ student.surname }}</td>
            </tr>
            <tr>
                <th>Date_naissance</th>
                <td>{{ student.dateNaissance ? student.dateNaissance|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_inscrit</th>
                <td>{{ student.dateInscrit ? student.dateInscrit|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Photo</th>
                <td>{{ student.photo }}</td>
            </tr>
            <tr>
                <th>Sexe</th>
                <td>{{ student.sexe }}</td>
            </tr>
            <tr>
                <th>Info_perso</th>
                <td>{{ student.infoPerso }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('student_index') }}">back to list</a>

    <a href="{{ path('student_edit', {'id': student.id}) }}">edit</a>

    {{ include('student/_delete_form.html.twig') }}
{% endblock %}